Microsoft Windows [Version 10.0.22000.978]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>code .

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
No changes detected

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
No changes detected

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
No changes detected

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py shell
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from firstapp.models import *




Microsoft Windows [Version 10.0.22000.978]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>code .

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
No changes detected

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
No changes detected

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
No changes detected

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py shell
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from firstapp.models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 4, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> from firstapp .models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 4, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> from firstapp.models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 4, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> from firstapp .models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 4, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> from firstapp .models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 4, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> cls
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'cls' is not defined
>>> clc
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'clc' is not defined
>>> from firstapp .models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 4, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> from firstapp.models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 4, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> from firstapp.models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas\firstapp\models.py", line 3, in <module>
    class Dojo(models.Model):
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class firstapp.models.Dojo doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> exit()

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
Migrations for 'firstapp':
  firstapp\migrations\0001_initial.py
    - Create model Dojo
    - Create model Ninja

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, firstapp, sessions
Running migrations:
  Applying firstapp.0001_initial... OK

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py shell
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from firstapp.models import *
>>> this_dojo = Dojo.objects.create(name = "Ahmed", city = "Ramallah" , state = "S")
>>> This_dojo.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'This_dojo' is not defined
>>> print(this_dojo)
Dojo object (1)
>>> This_dojo.objects.all().values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'This_dojo' is not defined
>>> this_dojo = Dojo.objects.create(name = "ziki", city = "TelAbeb" , state = "M5")
>>>
>>> this_dojo = Dojo.objects.create(name = "Lith", city = "TelAbeb" , state = "M")
>>> This_dojo.objects.all().values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'This_dojo' is not defined
>>> objects.all().values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'objects' is not defined
>>> Dojo.objects.create(name = "Lith", city = "TelAbeb" , state = "M")
<Dojo: Dojo object (4)>
>>> c = Dojo.objects.all()
>>> c.delete()
(4, {'firstapp.Dojo': 4})
>>> Dojo.objects.all()
<QuerySet []>
>>> this_dojo = Dojo.objects.create(name = "hamdan", city = "ramallah" , state = "M")
>>> this_dojo = Dojo.objects.create(name = "assi", city = "ramallah" , state = "M")
>>> this_dojo = Dojo.objects.create(name = "wheed", city = "ramallah" , state = "M")
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Ninja.objecta.get(id=4))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Ninja' has no attribute 'objecta'
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Ninja.objects.get(id=4))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
firstapp.models.Ninja.DoesNotExist: Ninja matching query does not exist.
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Dojo.objects.get(id=4))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
firstapp.models.Dojo.DoesNotExist: Dojo matching query does not exist.
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Dojo.objects.get(id=1))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
firstapp.models.Dojo.DoesNotExist: Dojo matching query does not exist.
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Dojo.objects.get(id=4))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
firstapp.models.Dojo.DoesNotExist: Dojo matching query does not exist.
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Dojo.objects.get(id=4))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Codey\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
firstapp.models.Dojo.DoesNotExist: Dojo matching query does not exist.
>>> Dojo.objects.all().values()
<QuerySet [{'id': 5, 'name': 'hamdan', 'city': 'ramallah', 'state': 'M', 'created_at': datetime.datetime(2022, 9, 26, 10, 32, 37, 414702, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 32, 37, 414702, tzinfo=datetime.timezone.utc)}, {'id': 6, 'name': 'assi', 'city': 'ramallah', 'state': 'M', 'created_at': datetime.datetime(2022, 9, 26, 10, 32, 49, 807255, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 32, 49, 807255, tzinfo=datetime.timezone.utc)}, {'id': 7, 'name': 'wheed', 'city': 'ramallah', 'state': 'M', 'created_at': datetime.datetime(2022, 9, 26, 10, 33, 4, 507699, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 33, 4, 507699, tzinfo=datetime.timezone.utc)}]>
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Dojo.objects.get(id=5))
>>> this_ninja= Ninja.objects.create(first_name="bbb",last_name="bb",dojo=Dojo.objects.get(id=5))
>>> this_ninja= Ninja.objects.create(first_name="ccc",last_name="cc",dojo=Dojo.objects.get(id=5))
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Dojo.objects.get(id=6))
>>> this_ninja= Ninja.objects.create(first_name="bbb",last_name="bb",dojo=Dojo.objects.get(id=6))
>>> this_ninja= Ninja.objects.create(first_name="ccc",last_name="cc",dojo=Dojo.objects.get(id=6))
>>> this_ninja= Ninja.objects.create(first_name="aaa",last_name="aa",dojo=Dojo.objects.get(id=7))
>>> this_ninja= Ninja.objects.create(first_name="bbb",last_name="bb",dojo=Dojo.objects.get(id=7))
>>> this_ninja= Ninja.objects.create(first_name="ccc",last_name="cc",dojo=Dojo.objects.get(id=7))
>>> Ninja.objects.filter(dojo = Dojo.objects.get(id = 5)
... )
<QuerySet [<Ninja: Ninja object (1)>, <Ninja: Ninja object (2)>, <Ninja: Ninja object (3)>]>
>>> Ninja.objects.filter(dojo = Dojo.objects.get(id = 5)).values()
<QuerySet [{'id': 1, 'first_name': 'aaa', 'last_name': 'aa', 'dojo_id': 5, 'created_at': datetime.datetime(2022, 9, 26, 10, 53, 15, 791388, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 53, 15, 791388, tzinfo=datetime.timezone.utc)}, {'id': 2, 'first_name': 'bbb', 'last_name': 'bb', 'dojo_id': 5, 'created_at': datetime.datetime(2022, 9, 26, 10, 54, 19, 753966, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 54, 19, 753966, tzinfo=datetime.timezone.utc)}, {'id': 3, 'first_name': 'ccc', 'last_name': 'cc', 'dojo_id': 5, 'created_at': datetime.datetime(2022, 9, 26, 10, 54, 35, 467951, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 54, 35, 467951, tzinfo=datetime.timezone.utc)}]>
>>> Ninja.objects.filter(dojo = Dojo.objects.last().values()
... )
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Dojo' object has no attribute 'values'
>>> Ninja.objects.filter(dojo = Dojo.objects.last().values())
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Dojo' object has no attribute 'values'
>>> Ninja.objects.filter(dojo = Dojo.objects.last()).values()
<QuerySet [{'id': 7, 'first_name': 'aaa', 'last_name': 'aa', 'dojo_id': 7, 'created_at': datetime.datetime(2022, 9, 26, 10, 55, 44, 227170, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 55, 44, 227170, tzinfo=datetime.timezone.utc)}, {'id': 8, 'first_name': 'bbb', 'last_name': 'bb', 'dojo_id': 7, 'created_at': datetime.datetime(2022, 9, 26, 10, 55, 52, 146525, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 55, 52, 146525, tzinfo=datetime.timezone.utc)}, {'id': 9, 'first_name': 'ccc', 'last_name': 'cc', 'dojo_id': 7, 'created_at': datetime.datetime(2022, 9, 26, 10, 56, 0, 725353, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2022, 9, 26, 10, 56, 0, 725353, tzinfo=datetime.timezone.utc)}]>
>>> exit()

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py makemigrations
It is impossible to add a non-nullable field 'desc' to dojo without specifying a default. This is because the database needs something to populate existing rows.
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit and manually define a default value in models.py.
Select an option: 1
Please enter the default value as valid Python.
The datetime and django.utils.timezone modules are available, so it is possible to provide e.g. timezone.now as a value.
Type 'exit' to exit this prompt
>>> "old dojo"
Migrations for 'firstapp':
  firstapp\migrations\0002_dojo_desc.py
    - Add field desc to dojo

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>
C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>Dojo.objects.all().values()
'Dojo.objects.all' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Codey\Desktop\CodingDojo\Python\Django\DojoNinjas>python manage.py shell
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> Dojo.objects.all().values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> Dojo.objects.get()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> Dojo.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> this_dojo = Dojo.objects.create(name = "newdojo", city = "ramallah" , state = "M")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> this_dojo
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'this_dojo' is not defined
>>> this_dojo.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'this_dojo' is not defined
>>> Dojo.objects.all().values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> Dojo.objects.all().__dict__
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> Dojo.objects.all().__dict__